var app = new Vue({
  el: '#app',
  data: {
    heading: ['States', 'Total Cases', 'Discharged', 'Deaths', 'Remaining'],
    reports: [
      {
        state: 'Abuja',
        overall_case: 41,
        discharged: 0,
        deaths: 2,
        remaining: 39,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Abia',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Adamawa',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Akwa Ibom',
        overall_case: 5,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Anambra',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Bauchi',
        overall_case: 3,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Bayelsa',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Benue',
        overall_case: 1,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Borno',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Cross River',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Delta',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Ebonyi',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Enugu',
        overall_case: 2,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Edo',
        overall_case: 7,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Ekiti',
        overall_case: 2,
        discharged: 1,
        deaths: 0,
        remaining: 1,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Gombe',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Imo',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Jigawa',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Kaduna',
        overall_case: 4,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Kano',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Katsina',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Kebbi',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Kogi',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Kwara',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Lagos',
        overall_case: 109,
        discharged: 17,
        deaths: 0,
        remaining: 92,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Nasarawa',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Niger',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Ogun',
        overall_case: 4,
        discharged: 2,
        deaths: 0,
        remaining: 2,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Ondo',
        overall_case: 1,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Osun',
        overall_case: 20,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Oyo',
        overall_case: 9,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Plateau',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Rivers',
        overall_case: 1,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '2nd April, 2020',
      },
      {
        state: 'Sokoto',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Taraba',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Yobe',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
      {
        state: 'Zamfara',
        overall_case: 0,
        discharged: 0,
        deaths: 0,
        remaining: 0,
        last_report: '',
      },
    ],
  },
})

google.charts.load('current', { packages: ['corechart'] })
google.charts.setOnLoadCallback(drawChart)

function drawChart() {
  var data = google.visualization.arrayToDataTable([
    ['Category', 'Number'],
    ['Total Cases', 209],
    ['Discharged', 25],
    ['Deaths', 4],
  ])

  var options = {
    title: 'Corona Data in Nigeria',
  }

  var chart = new google.visualization.PieChart(
    document.getElementById('piechart')
  )

  chart.draw(data, options)
}
